# Generated by Django 5.0.7 on 2024-08-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PadresTutores',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.docente')),
            ],
            options={
                'unique_together': {('id', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=45, null=True)),
                ('hora_modulo', models.CharField(blank=True, max_length=45, null=True)),
                ('turno', models.CharField(blank=True, max_length=45, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.materia')),
            ],
            options={
                'unique_together': {('id', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('padres_tutores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.padrestutores')),
            ],
            options={
                'unique_together': {('dni', 'padres_tutores')},
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('directivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.directivo')),
            ],
            options={
                'unique_together': {('dni', 'directivo')},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_curso', models.IntegerField()),
                ('num_division', models.IntegerField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, max_length=45, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=45, null=True)),
                ('comunicados', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.alumno')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.horario')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.preceptor')),
            ],
            options={
                'unique_together': {('num_curso', 'alumno', 'horario', 'preceptor')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.curso')),
            ],
            options={
                'unique_together': {('id', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='MesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_mesa', models.IntegerField()),
                ('num_mesa', models.IntegerField(blank=True, null=True)),
                ('num_orden', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.materia')),
            ],
            options={
                'unique_together': {('permiso_mesa', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('notas_timestre1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('notas_trimestre2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('notas_trimestre3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('notas_recuperacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.curso')),
            ],
            options={
                'unique_together': {('id', 'curso')},
            },
        ),
    ]
